version: "3"

services:
  web:
    container_name: web
    build:
      context: ./web/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - web

  worker:
    container_name: worker
    build:
      context: ./web/
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis