version: "3"

services:
  web:
    container_name: web
    build:
      context: ./web/
    ports:
      - "8000:8000"
  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web
