version: "3"

services:
  web:
    container_name: web
    build:
      context: web
    ports:
      - "8000:8000"
    volumes: ['./web:/web']
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  worker:
    container_name: worker
    build:
      context: web
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis